### ISSUE TITLE
Recommend replacing --mem-per-cpu with --mem in sbatch scripts

### ISSUE THREAD

**Issue by bdsinger** [PrincetonUniversity/prsonpipe#7]
Hi I help run the spock cluster at PNI, and we are tracking a bug in SLURM 17.11.9-2 where it doesn't handle the --mem-per-cpu arg well when a cluster has MaxMemPerCPU set, which we did (to 10G) until only a few minutes ago. Our config now matches Della which also does not have this limit.

I think the expectation is for SLURM to allocate you 3 cpus if you ask for, say, --mem-per-cpu=30G when MaxMemPerCPU is set to 10G (like it was for spock.) But for whatever reason this was not happening and an error was the result: no cpus would be allocated instead of 3 and sometimes slurm will crash soon after, we are still investigating.

If you use --mem  instead, I think it should work more consistently than --mem-per-cpu.

I realize this is more a SLURM bug than yours, but changing it will allow you to work around some SLURM bugs now and in the future most likely. Depending on mem-per-cpu to get you cores indirectly has a history of problems in SLURM it looks like according to the bug database at schedmd.com (the authors of SLURM.)

For now we have dropped our MaxMemPerCPU setting to match Della, but this could well be temporary, and we may need to set it again in the future. Please contact pnihelp if you have any questions!

**Comment by jnmildner** [comment]
Thanks! We replaced these calls a few months back, so updated versions already explicitly request a certain number of cores rather than relying on the mem-per-cpu flag. The script in question was from an older version. I'll double check to make sure there are no more scripts that use the mem-per-cpu flag in this way

**Comment by bdsinger** [comment]
To be clear the scripts in question are 
https://github.com/PrincetonUniversity/prsonpipe/blob/master/scripts/preprocess/sbatch_prep_FSL and friends, the ones with sbatch prefix (also _DARTEL and _SPM12W)

**Comment by jnmildner** [comment]
Yes, they're down to 10GB in this version which doesn't seem to cause any problems because that's just 1 cpu. I'll get rid of the mem-per-cpu flag entirely though, just to be safe
